/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package modul5pemvis;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class info extends javax.swing.JInternalFrame {
    private boolean isEdit = false;
    private int totalHarga;

 
    public info() {
        initComponents();
        tampil_data();
    }
    
    public void reset() {
        barang.setSelectedIndex(0);
        kode.setText(null);
        harga.setText(null);
        pembeli.setText(null);
        jumlah.setText(null);
        total.setText(null);
        bayar.setText(null);
        kembalian.setText(null);
    }
    
    public void tampil_data(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Pembeli");
        tabel.addColumn("Barang");
        tabel.addColumn("Kode");
        tabel.addColumn("Harga");
        tabel.addColumn("Jumlah");
        tabel.addColumn("Total");
        tabel.addColumn("Bayar");
        tabel.addColumn("Kembalian");
        
        try {
            java.sql.Connection conn = modul5pemvis.Modul5pemvis.koneksiDB();
            String query = "select * from jual";
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                Object [] row = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6),rs.getString(7),rs.getString(8)};
                tabel.addRow(row);
            }
            
            tabelinfo.setModel(tabel);
        } catch (Exception e) {
            e.printStackTrace();
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        Reset = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        Total = new javax.swing.JButton();
        Hitung = new javax.swing.JButton();
        bayar = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        kode = new javax.swing.JTextField();
        barang = new javax.swing.JComboBox<>();
        pembeli = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Hapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelinfo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reset.setBackground(new java.awt.Color(214, 201, 179));
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel3.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        Simpan.setBackground(new java.awt.Color(214, 201, 179));
        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        jPanel3.add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        Total.setBackground(new java.awt.Color(214, 201, 179));
        Total.setText("Total");
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        jPanel3.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        Hitung.setBackground(new java.awt.Color(214, 201, 179));
        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel3.add(Hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));
        jPanel3.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 130, -1));
        jPanel3.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 130, -1));

        kembalian.setEditable(false);
        jPanel3.add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 130, -1));
        jPanel3.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 130, -1));

        harga.setEditable(false);
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel3.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 130, -1));

        kode.setEditable(false);
        jPanel3.add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 130, -1));

        barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Paracetamol", "Komik", "Antangin", "Antimo", "Bodrek" }));
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });
        jPanel3.add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 130, -1));
        jPanel3.add(pembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 130, -1));

        jLabel10.setText("Total Pembayaran");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jLabel9.setText("Total Harga");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel8.setText("Nama Pembeli");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel7.setText("Jumlah Pembelian");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel6.setText("Kembalian");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel5.setText("Harga Barang");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel4.setText("Kode Barang");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel3.setText("Nama Barang");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\62813\\Pictures\\New folder\\53.jpg")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        tab.addTab("Inputan", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hapus.setBackground(new java.awt.Color(214, 201, 179));
        Hapus.setText("HAPUS");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel2.add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        tabelinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pembeli", "Barang", "Kode", "Harga", "Jumlah", "Total", "Bayar", "Kembali"
            }
        ));
        tabelinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelinfoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelinfo);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 560, 270));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\62813\\Pictures\\New folder\\53.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 604, -1));

        tab.addTab("Informasi", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
        // TODO add your handling code here:
        String pilbar = barang.getSelectedItem().toString();
        int Harga = 0;
        switch (pilbar) {
            case "Paracetamol" -> {
                kode.setText("001");
                Harga = 10000;
            }
            case "Komik" -> {
                kode.setText("002");
                Harga = 2000;
            }
            case "Antangin" -> {
                kode.setText("003");
                Harga = 3000;
            }
            case "Antimo" -> {
                kode.setText("004");
                Harga = 5000;
            }
            case "Bodrek" -> {
                kode.setText("004");
                Harga = 1000;
            }

            default -> {
                kode.setText("-");
                harga.setText("-");
            }
        }
         harga.setText(String.valueOf(Harga));
    }//GEN-LAST:event_barangActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        barang.setSelectedIndex(0);
        kode.setText(null);
        harga.setText(null);
        pembeli.setText(null);
        jumlah.setText(null);
        total.setText(null);
        bayar.setText(null);
        kembalian.setText(null);
    }//GEN-LAST:event_ResetActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        int Harga = Integer.parseInt(harga.getText());
        int Jumlah = Integer.parseInt(jumlah.getText());

        // Hitung total harga
        int totalHarga = Harga * Jumlah;

        // Tampilkan total harga pada komponen tampilan eTotal
        total.setText(String.valueOf(totalHarga));
    }//GEN-LAST:event_HitungActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
        int Bayar = Integer.parseInt(bayar.getText());

        // Ambil total harga dari komponen tampilan
        int totalHarga = Integer.parseInt(total.getText());

        // Hitung kembalian
        int Kembalian = Bayar - totalHarga;

        if (Kembalian < 0) {
            // Kembalian negatif, tampilkan pesan kesalahan
            JOptionPane.showMessageDialog(null, "Maaf, uang yang Anda bayarkan tidak mencukupi. Uang kurang sebesar: Rp " + Math.abs(Kembalian));
            kembalian.setText("Rp 0"); // Atur kembalian menjadi 0
        } else {
            // Tampilkan kembalian pada komponen tampilan eKembalian
            kembalian.setText("Rp " + Kembalian);
}
    }//GEN-LAST:event_TotalActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        try {
        String namabarang = (String) barang.getSelectedItem();
        String Kode = kode.getText();
        String Harga = harga.getText();
        String namapembeli = pembeli.getText();
        String Jumlah = jumlah.getText();
        String Total = total.getText();
        String Bayar = bayar.getText();
        String Kembali = kembalian.getText();

        if (namabarang.equals("Pilihan") || Kode.isEmpty() || Harga.isEmpty() || namapembeli.isEmpty() || Jumlah.isEmpty() || Total.isEmpty() || Bayar.isEmpty() || Kembali.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi semua kolom data terlebih dahulu.");
        } else {
            if (isEdit) {
                int selectedRow = tabelinfo.getSelectedRow();
                String namapembeliToUpdate = (String) tabelinfo.getValueAt(selectedRow, 0); // Ganti dengan kolom yang sesuai
                String sql = "UPDATE jual SET namapembeli = ?,namabarang = ?, kode = ?, harga = ?,  jumlah = ?, total = ?, bayar = ?, kembalian = ? WHERE namapembeli = ?";
                java.sql.Connection conn = modul5pemvis.Modul5pemvis.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, namapembeli);
                pst.setString(2, namabarang);
                pst.setString(3, Kode);
                pst.setString(4, Harga);               
                pst.setString(5, Jumlah);
                pst.setString(6, Total);
                pst.setString(7, Bayar);
                pst.setString(8, Kembali);
                pst.setString(9, namapembeliToUpdate);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data berhasil diupdate.");
                isEdit = false;
                Simpan.setText("Simpan");
            } else {
                // Mode Simpan: Simpan data baru
                String sql = "INSERT INTO jual (namapembeli, namabarang, kode, harga,  jumlah, total, bayar, kembalian) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                java.sql.Connection conn = modul5pemvis.Modul5pemvis.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, namapembeli);
                pst.setString(2, namabarang);
                pst.setString(3, Kode);
                pst.setString(4, Harga); 
                pst.setString(5, Jumlah);
                pst.setString(6, Total);
                pst.setString(7, Bayar);
                pst.setString(8, Kembali);
                pst.executeUpdate();
                tab.setSelectedIndex(1);
                JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            }
            reset();
            tampil_data();
            }

            tampil_data();
            tab.setSelectedIndex(1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
}

    }//GEN-LAST:event_SimpanActionPerformed

    private void tabelinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelinfoMouseClicked
        // TODO add your handling code here:
        int selectedRow = tabelinfo.getSelectedRow();

        if (selectedRow != -1) {
            String namaValue = (String) tabelinfo.getValueAt(selectedRow, 0);
            String barangValue = (String) tabelinfo.getValueAt(selectedRow, 1);
            String kodeValue = (String) tabelinfo.getValueAt(selectedRow, 2);
            String hargaValue = (String) tabelinfo.getValueAt(selectedRow, 3);
            String jumlahValue = (String) tabelinfo.getValueAt(selectedRow, 4);
            String totalValue = (String) tabelinfo.getValueAt(selectedRow, 5);
            String bayarValue = (String) tabelinfo.getValueAt(selectedRow, 6);
            String kembalianValue = (String) tabelinfo.getValueAt(selectedRow, 7);

            barang.setSelectedItem(barangValue);
            kode.setText(kodeValue);
            harga.setText(hargaValue);
            pembeli.setText(namaValue);
            jumlah.setText(jumlahValue);
            total.setText(totalValue);
            bayar.setText(bayarValue);
            kembalian.setText(kembalianValue);

            // Mengaktifkan tombol Edit
            Simpan.setText("Edit");
            isEdit = true; // Menandai bahwa ini adalah mode edit
}
    }//GEN-LAST:event_tabelinfoMouseClicked

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelinfo.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus.");
        } else {
            int option = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) {
                try {
                    String namabarangToDelete = (String)tabelinfo.getValueAt(selectedRow, 0);
                    String sql = "DELETE FROM jual WHERE namapembeli = ?";
                    java.sql.Connection conn = (java.sql.Connection) modul5pemvis.Modul5pemvis.koneksiDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, namabarangToDelete);
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
                    tampil_data();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus data.");
                    System.out.println(e.getMessage());
                }
       }
}
    }//GEN-LAST:event_HapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Hitung;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Simpan;
    private javax.swing.JButton Total;
    private javax.swing.JComboBox<String> barang;
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField pembeli;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tabelinfo;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
